name: Deploy BedrockChatbot

permissions:
  id-token: write # Required for GitHub to be able to create a token for you to authenticate with AWS
  contents: read  # Permits your action to read this repo.

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    environment: test
    
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        AWS_DEFAULT_OUTPUT: json
        allowListDomain : ${{ vars.ALLOW_LIST_DOMAIN }}
      run: |
        #apt-get update -qy
        #apt-get install -y curl gnupg software-properties-common
        #apt-get install -y unzip
      
          # Install Python 3
          #sudo apt-get install -y python3 python3-pip
      
          # Install Git (usually pre-installed in GitLab runners)
          #sudo apt-get install -y git
      
          # Install jq
          sudo apt-get install -y jq
      
          # Install AWS CLI
          #curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          #unzip awscliv2.zip
          #./aws/install

          # Install AWS CDK
          npm install -g aws-cdk

          python3 --version
          git --version
          node --version
          jq --version
          aws --version
          cdk --version

          cd cdk
          python3 -m venv .venv
          source .venv/bin/activate
          python3 -m pip install -r requirements.txt
          cd ..

          chmod u+x ./deploy.sh
          ./deploy.sh

          
      shell: bash
